version: "3.7"

# environment
x-volumes: &server-volume
  BROWSER_HOST: "http://localhost:8000"
  SECRET_KEY: "b8e94e40e79ddd8cfd508c7ae36b8fa17b5a1e58e4b80e75bb0e193df8c4333b"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: nayan32biswas/django_crud:latest
    container_name: django_crud
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      <<: *server-volume
    volumes:
      - ./server/:/app/server/
