version: "3.7"

# environment
x-volumes: &server-volume
  HOST_URL: "http://localhost:8000"
  SECRET_KEY: "6r)%9(f7w_h3t2d_kh2+=-rhg+#8s*hl7k)yij=e=6)qxmz72z"

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: nayan32biswas/django_crud:latest
    container_name: django_crud
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      <<: *server-volume
    volumes:
      - ./server/:/app/server/
